name: Release

on:
    push:
        branches:
            - master
            - beta

jobs:
    prepare:
        runs-on: ubuntu-latest
        if: "! contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - run: echo "${{ github.event.head_commit.message }}"
    publish:
        needs: prepare
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: |
                  npm ci --ignore-scripts
            - name: Build
              run: |
                  npm run build
            - run: npm install @semantic-release/changelog @semantic-release/git --ignore-scripts --no-save
            - uses: codfish/semantic-release-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
